### ISSUE TITLE
feature_request(behavior): automatic opening of sources on specific sites

### ISSUE THREAD

**Issue by Kristinita** [CarlosAMolina/checkIframe#1]
### 1. Summary

It would be nice, if “Check iframe” will have the option — automatic opening of iframe sources on sites selected by user.

#### 2.1. Settings

“Check iframe” will have the new setting `Sites where sources open automatically`. My example values:

```text
sci-hub.se
sci-hub.do
```

#### 2.2. Behavior

User opens any page on the **<https://sci-hub.se>** site, for example, **<https://sci-hub.se/https://www.ingentaconnect.com/content/lwish/sou/2014/00000057/00000057/art00007>**. We can see 1 `iframe` tag with a direct link to the source:

![Sci-Hub.se direct link](https://i.imgur.com/lIaZlhu.png)

“Check iframe” will open [**this link**](https://twin.sci-hub.se/5670/79bb64293bddeff5c422d5779b2ec002/glaser2014.pdf) in the current tab.

Or if user visits **<https://sci-hub.do/10.1080/14767430.2019.1572942>**, he will automatically be redirected to the **<https://dacemirror.sci-hub.do/journal-article/243ed3def87c3343ba3d2556cd240bf9/richards2019.pdf>** page.

![Sci-Hub.do direct link](https://i.imgur.com/tedvY16.png)

#### 3.1. Common cause

Automation.

#### 3.2. Details

Sci-Hub is the most visited site for me. I constantly manually use “Check iframe” that open PDF file directly on the browser without the Sci-Hub wrapper. It takes a lot of my time.

Reason of my behavior — I can make [**hyperlinks to the specific pages**](https://acrobatusers.com/tutorials/can-i-hyperlink-specific-page-pdf-file/) for the convenience of users. Example:

1. **<https://dacemirror.sci-hub.do/journal-article/243ed3def87c3343ba3d2556cd240bf9/richards2019.pdf#page=4>** — will works
1. **<https://sci-hub.do/10.1080/14767430.2019.1572942#page=4>** — no.

Thanks.

**Comment by CarlosAMolina** [comment]
Hi Kristinita,

I am glad to see the addon helps :) Thank you very much for your interest and the clear explanation of the new feature.

I will work on it. Regards!

**Comment by CarlosAMolina** [comment]
Hello @Kristinita,

I just uploaded to Mozilla's Addons the version 1.4.0 which applies the redirection.

As you said, the settings have the new option 'Sites where first source opens automatically' where you can set your desired websites, for example:

~~~
sci-hub.se
sci-hub.do
~~~

If the webpage has more than one iframe, the first source will be used as the redirection location. You can use the blacklist option (Sources to avoid listing) to omit undesired redirections.

Note. If the redirection does not apply automatically, try reloading the page. Please, notify me any strange behavior.

I hope this helps!
