### ISSUE TITLE
Iframe is not highlighted with red border - Firefox for Android

### ISSUE THREAD

**Issue by CarlosAMolina** [CarlosAMolina/checkIframe#7]
```
Sorry, but does not work for me.

With Firefox desktop edition, I have set the following CSS code in usercontent.css:

iframe{border-style: solid !important; border-widh:2px !important; border-color:#00ff00 !important; overflow: auto !important;}

This should beware me from malicious addons manipulating Google search results as happened to me in the past.

As shown at your images -advertising the CheckIframe addon- your addon should expose any iframe with a red border:

https://addons.mozilla.org/user-media/previews/full/203/203354.png

This does not happen here.
Tested at:

https://www.w3schools.com/html/html_iframe.asp
```
_Originally posted by @seniordevel in https://github.com/CarlosAMolina/checkIframe/issues/3#issuecomment-2294981421_

**Comment by CarlosAMolina** [comment]
Hi @seniordevel,

I've just checked the web <https://www.w3schools.com/html/html_iframe.asp> and the add-on shows the red border correctly.

Please note that the red border does not appear automatically, you have to click the `Scroll to element` button of the add-on ([explained in this documentation link](https://cmoli.es/projects/check-iframe/how-to-use/scroll.html)). Are you clicking the button?

Another point is that the add-on is detecting 18 `iframe` tags in your page, each time you click the `Scroll to element` button, the add-on tries to highlight the next tag, but on your page only one tag can be highlighted (the tag with source <https://www.w3schools.com/html/default.asp>). Each time you click the button, the add-on displays the message `Tag iframe: source X/18` (where `X` represents the tag index, in this case numbers from 1 to 18). Please click the button until you are in the tag with URL <https://www.w3schools.com/html/default.asp> and check if the red border appears, when I checked the web, the tag with source <https://www.w3schools.com/html/default.asp> to highlight was the first one, so I only had to click the button once, you can know the index of the tag by clicking he `Show tags info` button ([explained in this documentation link](https://cmoli.es/projects/check-iframe/how-to-use/show-tags-info.html)).

If this does not work, please repeat it but without modifying the `usercontent.css` file.

I look forward to your results.

**Comment by seniordevel** [comment]
> Please note that the red border does not appear automatically,

Thanks, this was my misunderstanding.

Now everything works fine:
![Screenshot_20240818-134445](https://github.com/user-attachments/assets/f12cfb0e-6024-4503-a68f-979aedd5710d)

However, I was looking for an addon to do this automatically at any page and for all iframes without user action.

Maybe you like to add a simple preference to allow automatic highlighting?

I am using the Iceraven Firefox fork on Android. This fork allows Android users to access about:config settigs:
https://github.com/fork-maintainers/iceraven-browser

**Comment by CarlosAMolina** [comment]
Great :) I'm happy to see that is solved.

Thanks, I've just updated the title.

Yes, the new functionality you comment can be added, I just created this  https://github.com/CarlosAMolina/checkIframe/issues/8 issue with the new request, please check it and if the described behavior is not correct feel free to create a new one with the correct needs. I'll work on it but I don't know how much time I'll need as it is a project I work on in my free time, but I'll let you know as soon as it is ready.

Regards!
